package com.joebrooks.showmethecoin.trade.upbit.client;

import lombok.Getter;

@Getter
public enum CoinType {
    BTC("KRW-BTC", "비트코인"),
    ETH("KRW-ETH", "이더리움"),
    BCH("KRW-BCH", "비트코인캐시"),
    AAVE("KRW-AAVE", "에이브"),
    BSV("KRW-BSV", "비트코인에스브이"),
    SOL("KRW-SOL", "솔라나"),
    ETC("KRW-ETC", "이더리움클래식"),
    BTG("KRW-BTG", "비트코인골드"),
    AVAX("KRW-AVAX", "아발란체"),
    STRK("KRW-STRK", "스트라이크"),
    ASX("KRW-ASX", "엑시인피니티"),
    ATOM("KRW-ATOM", "코스모스"),
    NEO("KRW-NEO", "네오"),
    REP("KRW-REP", "어거"),
    DOT("KRW-DOT", "폴카닷"),
    LINK("KRW-LINK", "체인링크"),
    WAVES("KRW-WAVES", "웨이브"),
    NEAR("KRW-NEAR", "니어프로토콜"),
    QTUM("KRW-QTUM", "퀀텀"),
    SBD("KRW-SBD", "스팀달러"),
    GAS("KRW-GAS", "가스"),
    FLOW("KRW-FLOW", "플로우"),
    WEMIX("KRW-WEMIX", "위믹스"),
    OMG("KRW-OMG", "오미세고"),
    KAVA("KRW-KAVA", "카바"),
    TON("KRW-TON", "톤"),
    XTZ("KRW-XTZ", "테조스"),
    KNC("KRW-KNC", "카이버네트워크"),
    AQT("KRW-AQT", "알파쿼크"),
    THETA("KRW-THETA", "쎄타토큰"),
    MTL("KRW-MTL", "메탈"),
    SAND("KRW-SAND", "샌드박스"),
    EOS("KRW-EOS", "이오스"),
    LST("KRW-LSK", "리스크"),
    CBK("KRW-CBK", "코박토큰"),
    GMT("KRW-GMT", "스테픈"),
    CELO("KRW-CELO", "셀로"),
    MANA("KRW-MANA", "디센트럴랜드"),
    SRM("KRW-SRM", "세럼"),
    DAWN("KRW-DAWN", "던프로토콜"),
    MATIC("KRW-MATIC", "폴리곤"),
    STRAX("KRW-STRAX", "스트라티스"),
    STORJ("KRW-STORJ", "스토리지"),
    ENJ("KRW_ENJ", "엔진코인"),
    PUNDIX("KRW-PUNDIX", "펀디엑스"),
    HIVE("KRW-HIVE", "하이브"),
    ADA("KRW-ADA", "에이다"),
    ARK("KRW-ARK", "아크"),
    HUNT("KRW-HUNT", "헌트"),
    SXP("KRW-SXP", "솔라"),
    STX("KRW-STX", "스택스"),
    ONG("KRW-ONG", "온톨로지가스"),
    BAT("KRW-BAT", "베이직어텐션토큰"),
    PLA("KRW-PLA", "플레이댑"),
    MLK("KRW-MLK", "밀크"),
    GRS("KRW-GRS", "그로스톨코인"),
    XRP("KRW-XRP", "리플"),
    ZRX("KRW-ZRX", "제로엑스"),
    BORA("KRW-BORA", "보라"),
    ALGO("KRW-ALGO", "알고랜드"),
    ICX("KRW-ICX", "아이콘"),
    IOTA("KRW-IOTA", "아이오타"),
    GLM("KRW-GLM", "골렘"),
    ONT("KRW-ONT", "온톨로지"),
    STEEM("KRW-STEEM", "스팀"),
    POWR("KRW-POWR", "파워렛저"),
    POLY("KRW-POLY", "폴리매쓰"),
    CHZ("KRW-CHZ", "칠리즈"),
    CVC("KRW-CVC", "시빅"),
    HUM("KRW-HUM", "휴먼스케이프"),
    ELF("KRW-ELF", "엘프"),
    CRO("KRW-CRO", "크로노스"),
    AERGO("KRW-AERGO", "아르고"),
    WAXP("KRW-WAXP", "왁스"),
    XLM("KRW-XLM", "스텔라루멘"),
    ARDR("KRW-ARDR", "아더"),
    MOC("KRW-MOC", "모스코인"),
    UPP("KRW-UPP", "센티넬프로토콜"),
    HBAR("KRW-HBAR", "헤데라"),
    FCT2("KRW-FCT2", "피르마체인"),
    TFUEL("KRW-TFUEL", "쎄타퓨엘"),
    TRX("KRW-TRX", "트론"),
    DKA("KRW-DKA", "디카르고"),
    LOOM("KRW-LOOM", "룸네트워크"),
    XEM("KRW-XEM", "넴"),
    STPT("KRW-STPT", "에스티피"),
    ANKR("KRW-ANKR", "앵커"),
    ORBS("KRW-ORBS", "오브스"),
    ZIL("KRW-ZIL", "질리카"),
    META("KRW-META", "메타디움"),
    T("KRW-T", "쓰레스홀드"),
    SNT("KRW-SNT", "스테이터스네트워크토큰"),
    JST("KRW-JST", "저스트"),
    VET("KRW-VET", "비체인"),
    SSX("KRW-SSX", "썸씽"),
    MED("KRW-MED", "메디블록"),
    IOST("KRW-IOST", "아이오에스티"),
    QKC("KRW-QKC", "쿼크체인"),
    STMX("KRW-STMX", "스톰엑스"),
    RFR("KRW-RFR", "리퍼리움"),
    AHT("KRW-ATH", "아하토큰"),
    TT("KRW-TT", "썬더코어"),
    IQ("KRW-IQ", "에브리피디아"),
    MFT("KRW-MFT", "메인프레임"),
    MVL("KRW-MVL", "엠블"),
    CRE("KRW-CRE", "캐리프로토콜"),
    SC("KRW-SC", "시아코인"),
    MBL("KRW-MBL", "무비블록"),
    XEC("KRW-XEC", "이캐시");



    private String name;
    private String koreanName;

    private CoinType(String name, String koreanName){
        this.name = name;
        this.koreanName = koreanName;
    }
}
